OAuthIssuer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAuthIssuer.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

OAuthIssuer/Controllers/OAuthIssuerController.cs
using System.Web.Mvc;
using DotNetOpenAuth.OAuth2;
using System.Security.Cryptography.X509Certificates;
using DotNetOpenAuth.Messaging;
using OAuthIssuer.Infrastructure;

namespace OAuthIssuer.Controllers
{
public class OAuthIssuerController : Controller
{
    public ActionResult Index()
    {
        var configuration = new IssuerConfiguration
        {
            EncryptionCertificate = new X509Certificate2(Server.MapPath("~/Certs/localhost.cer")),
            SigningCertificate = new X509Certificate2(Server.MapPath("~/Certs/localhost.pfx"), "a")
        };

        var authorizationServer = new AuthorizationServer(new OAuth2Issuer(configuration));
        var response = authorizationServer.HandleTokenRequest(Request).AsActionResult();

        return response;
    }
}
}

OAuthIssuer/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
    OAuth2 Token Issuer is @Html.ActionLink("here", "Index", "OAuthIssuer")
        
    </div>
</body>
</html>